### ISSUE TITLE
idea: This plugin can categorize highlight link with icon.

### ISSUE THREAD

**Issue by Connor-yang96** [mdelobelle/obsidian_supercharged_links#1]
When I'm seeing this plugin can give a backlink to the background , an icon , and category. 

The idea is comming.  It looks like give a highlight text to an icon and category. 
You know the highlight text have the background , but the highlight text can't be with an icon and can't be categorized.

So, if there's a way that convert highlight text to the backlink with highlight link folder. 

and then use this plugin for categorize highlight link with icon. 

That's really really wonderful. 

Appreciate your plugin.

**Comment by mdelobelle** [comment]
Hi!
If I understand your need correctly, I think the best way to achieved that is to use a combination of Note Refactor plugin and Supercharged Links:
With Note Refactor you can select the text you want to highlight and choose the "Extract Selection to new note - first line as file name" -> it will create a new file in which you can specify a category; and in your source note, it will replace the text by a backlink that will benefit from this styling
