### ISSUE TITLE
Bug & Suggestion about the property manager

### ISSUE THREAD

**Issue by Tony-zf1** [mdelobelle/obsidian_supercharged_links#10]
If we have too many values, the "Add" ,"√","×" buttons can't be reached like the figure below.
![image](https://user-images.githubusercontent.com/79450935/119249734-7f198200-bbcd-11eb-9cb7-a9dab0973ba1.png)

Can we preset the values directly by typing the text ?
![image](https://user-images.githubusercontent.com/79450935/119249797-2ac2d200-bbce-11eb-81eb-662a665de09b.png)

Thank you!

**Comment by mdelobelle** [comment]
Hi. this setting modal is not scrollable at the moment.
If you have long list of preset values, I suggest that you create a note for it,
You fill this note with one value per line
You put the note's path in the field above : 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/1233240/119254996-98183800-bbb9-11eb-813a-cdaa2da1968d.png">

Does that satisfy your need?

**Comment by Tony-zf1** [comment]
> Hi. this setting modal is not scrollable at the moment.
> If you have long list of preset values, I suggest that you create a note for it,
> You fill this note with one value per line
> You put the note's path in the field above :
> 
> <img alt="image" width="592" src="https://user-images.githubusercontent.com/1233240/119254996-98183800-bbb9-11eb-813a-cdaa2da1968d.png">
> 
> Does that satisfy your need?

It works well indeed. 
Thank you so much!
