### ISSUE TITLE
ignore certain frontmatter/dataview fields

### ISSUE THREAD

**Issue by weeyizhi** [mdelobelle/obsidian_supercharged_links#11]
For files with many metadata fields, right-clicking them turn messy. I would like to suggest the ability to ignore certain fields.

Suggestions:
a) ignore fields that are listed as an array
b) capability to toggle regex matching for fields

**Comment by mdelobelle** [comment]
Hi this is now almost possible with Supercharged Links 0.2.5
with a note containing the fields to whitelist in your menu
Could you test it and give me your feedback?

**Comment by weeyizhi** [comment]
Hi there. I gave this a test and it seems to be working well. Now that I think about it, perhaps regex support on this would be a bit of an overkill since most people would not use it. I'm happy with the feature as is, so feel free to close this if you think regex is not needed :)

**Comment by mdelobelle** [comment]
thanks!
