### ISSUE TITLE
Can this plugin use with obsidian-icon-shortcodes？

### ISSUE THREAD

**Issue by PencilMing** [mdelobelle/obsidian_supercharged_links#116]
I found this plugin is also awesome [obsidian-icon-shortcodes](https://github.com/aidenlx/obsidian-icon-shortcodes), if the supercharged link can use with it, it will be wonderful. That plugin has API maybe it's not difficult.

**Comment by PencilMing** [comment]
link favicon就有用这个api

_Originally posted by @aidenlx in https://github.com/aidenlx/obsidian-icon-shortcodes/issues/50#issuecomment-1146564052_

**Comment by HEmile** [comment]
I'll close this as the new more general issue #187 encompasses it.
