### ISSUE TITLE
BUG: PNG file shows Supercharged Link active

### ISSUE THREAD

**Issue by namtrah** [mdelobelle/obsidian_supercharged_links#121]
I have a PNG file that is highlighted with a supercharged link. I presume that some algorithm mistakenly finds the attribute I use... Totally weird. Be glad to upload what I can to help. Just not sure what you would need to recreate.

![image](https://user-images.githubusercontent.com/13903735/173239065-d6a99662-735c-4247-9d01-020fd1054c75.png)

![image](https://user-images.githubusercontent.com/13903735/173239049-8fc2d753-4d14-4625-bc4a-4951078ee06d.png)

**Comment by HEmile** [comment]
Are you missing an exclamation mark to the embed of the image link? SL doesn't distinguish between links to notes and links to files... if needed you can do some css on the path to filter this out

**Comment by namtrah** [comment]
Sorry, I wasn't clear. The second image above is from the left hand side bar in Obsidian's own File Explorer. I didn't add anything of the sort.

**Comment by namtrah** [comment]
If you want, I could send you the actual file over DM (in Discord?)

**Comment by OptionalM** [comment]
@namtrah Do you have an `.md` file with the same name? This might be another case of #163

**Comment by namtrah** [comment]
In fact, I do have a `.md` file with the same Player's name.

**Comment by OptionalM** [comment]
Then this will be fixed when [my PR gets merged](https://github.com/mdelobelle/obsidian_supercharged_links/pull/179).
