### ISSUE TITLE
Bug: Conflict with Another Quick Switcher's Hotkey indicators

### ISSUE THREAD

**Issue by chrisgrieser** [mdelobelle/obsidian_supercharged_links#122]
Not sure what causes this (otherwise I'd fix it myself via PR), but it seems that with the recent Another Quick Switcher update that introduced hotkey guides, the first 9 entries (the one with hotkey guide) do not get the `data-link...` cssclasses, while the remaining entries do. The weird thing is that the css classes are still *exactly* the same 😵‍💫 

(maybe related to #109?)

![image](https://user-images.githubusercontent.com/73286100/173319396-a8c280dc-c5fa-414a-8bea-a8e93a0ced1d.png)

**Comment by kometenstaub** [comment]
This is fixed.
