### ISSUE TITLE
FR: Make the plugin also apply to tabs (0.16)

### ISSUE THREAD

**Issue by chrisgrieser** [mdelobelle/obsidian_supercharged_links#136]
with 0.16, we get tabs, and it would be nice to add icons to the tabs, similar to the browser.
<img width="657" alt="Pasted image 2022-08-31 07 37 20" src="https://user-images.githubusercontent.com/73286100/187600611-efc1f69b-18dd-43da-aa48-6d11d354f361.png">

**Comment by HEmile** [comment]
Oh, good idea!

**Comment by chrisgrieser** [comment]
well, that was quick 🥰

**Comment by chrisgrieser** [comment]
Unfortunately, there seem to be some bugs with it currently.


The icon only gets applied to the first tab
<img width="876" alt="Pasted image 2022-09-12 13 16 34" src="https://user-images.githubusercontent.com/73286100/189640325-3594098f-9ee2-4118-a8b8-0017be072adc.png">

The icon does not update when switching to another note in that tab
![Kapture 2022-09-12 at 13 18 13](https://user-images.githubusercontent.com/73286100/189640635-7516297d-8ee5-4e04-b025-5c7767b310c4.gif)

**Comment by HEmile** [comment]
I see, I think I should refresh the loading more often.

**Comment by HEmile** [comment]
Can you try in the new version? Should be better now.

**Comment by chrisgrieser** [comment]
This resolved the first issue completely and the second one mostly, thanks!

the only issue remaining is that *newly created* tabs or panes do not have any icon yet initially, be they do get icons once you switch to another note

**Comment by HEmile** [comment]
Okay, using layout-change now, all these issues seem to work on my end and performance is fine for now on my laptop.
