### ISSUE TITLE
No Supercharged Links option in Style Settings 

### ISSUE THREAD

**Issue by foenixp** [mdelobelle/obsidian_supercharged_links#137]
I just installed Supercharged Links and couldn't use it since there is no Supercharged Links option in the Style Settings. I tested it with the current Obsidian public version, the insider's most recent version, and sandbox. But none of them worked.
Below is with the sandbox:
![image](https://user-images.githubusercontent.com/102443314/188178610-b23b7460-e7b5-42b4-8a5f-03444d8b5d97.png)

**Comment by HEmile** [comment]
Did you make sure to create at least one selector in the settings of Supercharged Links? Can you show the settings of Supercharged Links?

It shouldn't show up anything unless you set up a selector there.

**Comment by foenixp** [comment]
Yes, I created 2 selectors. 
![image](https://user-images.githubusercontent.com/102443314/188506668-f687c2b8-48c1-4680-9991-c3bd23ed5daa.png)
![image](https://user-images.githubusercontent.com/102443314/188506676-54916842-e759-4096-9e70-172bc3c5ee56.png)
![image](https://user-images.githubusercontent.com/102443314/188506683-4a15b73b-8c39-4d7d-b4ff-a3a3b7a11c1c.png)

**Comment by HEmile** [comment]
Hmm... Can you check if the supercharged-link-gen.css snippet is enabled under Appearance -> Snippets? It should've automatically done this. If it's enabled, can you share what is in this file?

**Comment by foenixp** [comment]
> Hmm... Can you check if the supercharged-link-gen.css snippet is enabled under Appearance -> Snippets? It should've automatically done this. If it's enabled, can you share what is in this file?

Oh, that's the issue! The css wasn't on. After I enable it, now I can see the Supercharged Link under the Style Settings plugin. Thank you!

**Comment by SunflowerFuture** [comment]
Having the same exact problem here, on iPadOS 17.3.1; I have defined a selector, the css snippet is on, but nothing showing up in Style Settings. Help!
