### ISSUE TITLE
SL not loading on Obsidian startup 

### ISSUE THREAD

**Issue by isedwinr** [mdelobelle/obsidian_supercharged_links#144]
Hi, not a big issue but just to let you know

When starting/opening Obsidian, the SL plugin does not load automatically. Also the SL settings do not show up in the Style Settings Plugin
Only after opening (without any action taken) the SL plugin starts and also shows again in the styl;e settings 

Turned off other (external) plugins to see if they conflict but nothing changed
Obsidian v0.16.5 on Windows 10

**Comment by franciskafieh** [comment]
This would be fixed by #143. For now, I would suggest using the PR author's patch fork. You can do this by manually installing or with BRAT. LMK if you need help

**Comment by HEmile** [comment]
I didn't realise this caused SL not to load. I'm on vacation so i can't build the plugin until next week...

**Comment by timothymhuang** [comment]
@franciskafieh Hi sorry for writing a comment late, but I would like help with this. I installed BRAT within Obsidian, then tried to "Add Beta plugin": `https://github.com/dsummersl/obsidian_supercharged_links`
I got the error "The release is not complete and cannot download. main.js is missing from the Release." Are you able to help?
Thank you

**Comment by franciskafieh** [comment]
> @franciskafieh Hi sorry for writing a comment late, but I would like help with this. I installed BRAT within Obsidian, then tried to "Add Beta plugin": `https://github.com/dsummersl/obsidian_supercharged_links` I got the error "The release is not complete and cannot download. main.js is missing from the Release." Are you able to help? Thank you

the link to the PR should be https://github.com/johanfriis/obsidian_supercharged_links

**Comment by timothymhuang** [comment]
> > @franciskafieh Hi sorry for writing a comment late, but I would like help with this. I installed BRAT within Obsidian, then tried to "Add Beta plugin": `https://github.com/dsummersl/obsidian_supercharged_links` I got the error "The release is not complete and cannot download. main.js is missing from the Release." Are you able to help? Thank you
> 
> the link to the repo used in the PR (#143) should be https://github.com/johanfriis/obsidian_supercharged_links

I used that URL and I got the same error message. I even tried to make a fork and add a release, but that didn't work either. Any suggestions? Thank you.

**Comment by franciskafieh** [comment]
> 

whoops, my bad, forgot how BRAT worked lol. I mean you could always just build the main.js file yourself and simply replace the one that is in your .obsidian/plugins/obsidian-supercharged-links (or whatever it's called) folder.


Steps to build main.js:

(node.js and git as pre-requisites)
1. `git clone https://github.com/johanfriis/obsidian_supercharged_links` to clone the project locally
2. cd `obsidian_supercharged_links`
3. `npm i` (wait for it to finish installing dependencies)
4. `npm run build` (once done, it will produce a main.js file in this project folder that you can use to replace your exisiting main.js file.

also, if @johanfriis has time, they could add a release to their fork for people to use BRAT with for now. author of this plugin still seems to be AWOL

**Comment by timothymhuang** [comment]
Thank you, this worked. Unfortunately, it didn't solve the startup problem. I may tinker around with it some more, but I am probably just going to wait.

**Comment by t3mujin** [comment]
Any updates on this? The patch didn't work for me also, and there hasn't been changes for months.

**Comment by franciskafieh** [comment]
hey @HEmile, this can be closed now i think. everything works fine on my machine. thanks so much for the merge and update!

**Comment by HEmile** [comment]
Thanks for mentioning!
