### ISSUE TITLE
Feature Request: Prevent customization from showing up in the tabs.

### ISSUE THREAD

**Issue by Sriramgireesh** [mdelobelle/obsidian_supercharged_links#145]
Would it be possible to introduce an option to remove the customizations for links do not show up in the tabs names displayed above the contents of the file? In stacked view, they are rather distracting.

**Comment by HEmile** [comment]
There should already be such an option in the latest release?

**Comment by Sriramgireesh** [comment]
> There should already be such an option in the latest release? Or maybe i misunderstand

Just checked you are correct. Thanks a lot.
