### ISSUE TITLE
Abnormal display in DataView

### ISSUE THREAD

**Issue by iris2jane** [mdelobelle/obsidian_supercharged_links#15]
In version 0.2.6, some icons cannot be displayed in DataView, which was normal in previous versions.
![image](https://user-images.githubusercontent.com/36763930/119614911-68736500-be31-11eb-9096-e3c6620a6aae.png)

**Comment by mdelobelle** [comment]
Hi, can you detail your settings and also the inline fields/ frontmatter fields that your are using for both a link that is properly rendered and one that isn't please?

**Comment by iris2jane** [comment]
Hello, I found that there are two cases about icons disappearing. One is that they disappear everywhere in the document; One is that only the Dataview disappears and other places display normally.

![image](https://user-images.githubusercontent.com/36763930/120075851-7d702280-c0d5-11eb-94be-685d36e5c463.png)
![image](https://user-images.githubusercontent.com/36763930/120075891-ae505780-c0d5-11eb-8361-45b4a52f0df7.png)


![image](https://user-images.githubusercontent.com/36763930/120075970-1010c180-c0d6-11eb-8396-dbdda9d49dd3.png)
![image](https://user-images.githubusercontent.com/36763930/120076031-5108d600-c0d6-11eb-8a36-6e57fbb8e6f6.png)

**Comment by mdelobelle** [comment]
Hi. 
I've reproduced something similar:
Can you check if there is a blank line at the top of your 1GAPHG file? 
If that's the case, the YAML won't be parsed so you'll have to remove it so that your file start with "---" at the top of the file

**Comment by iris2jane** [comment]
Yes, I did add one more blank line. Sorry for that!😂

And I find that the second situation described above may be caused by too much text in the document,
![image](https://user-images.githubusercontent.com/36763930/120189274-b9c48f80-c249-11eb-9a43-9e67e1f5a6e2.png)
![image](https://user-images.githubusercontent.com/36763930/120189460-f55f5980-c249-11eb-8ae6-c07a4f2e225d.png)

The normal one
![image](https://user-images.githubusercontent.com/36763930/120189764-50914c00-c24a-11eb-81db-6f83c653e017.png)

**Comment by mdelobelle** [comment]
Hello unfortunately this is caused by the capability of reading large files.
I've introduced a workaround in 0.2.10: you can now choose to exclude "inline fields" from being targeted. 
In this case, the plugin will only look for frontmatter attributes which is much faster and works also with very large files.

In the plugin settings, you'll have to toggle off this option:
<img width="536" alt="image" src="https://user-images.githubusercontent.com/1233240/120590335-a9bfd200-c43a-11eb-945e-9d5926ef81d2.png">
