### ISSUE TITLE
hi what is your obsidian themes

### ISSUE THREAD

**Issue by px39n** [mdelobelle/obsidian_supercharged_links#158]
hi what is your obsidian theme shown in the readme.

I really like it layout. I searched all the themes but I cannot find it.

**Comment by chrisgrieser** [comment]
It's [Primary](https://github.com/ceciliamay/obsidianmd-theme-primary), which unfortunately has not been upgraded for Obsidian 1.0 yet. 

(also, GitHub issues shouldn't be used for questions)

**Comment by px39n** [comment]
@chrisgrieser I am sorry I dont know issues cannot be used for questions. Thank you for reminding me that.
