### ISSUE TITLE
Issue with ignoring fields in context menu

### ISSUE THREAD

**Issue by NB574** [mdelobelle/obsidian_supercharged_links#16]
Hi, I’ve looked at the documentation for ignoring fields so that they don’t show in the context menu, but for some reason the fields are still showing, e.g.

![image](https://user-images.githubusercontent.com/80176672/119702002-42f85280-be55-11eb-9c9c-24082629792b.png)

still shows author in the context menu:

![image](https://user-images.githubusercontent.com/80176672/119701207-640c7380-be54-11eb-875e-9358af5174d4.png)

The metadata, which Dataview is taking its info from is:

![image](https://user-images.githubusercontent.com/80176672/119701476-aa61d280-be54-11eb-980d-bfe3625f65bd.png)

Also the field update options sometimes show at the top of the context menu, instead of under a divider, other times they show at the bottom of the context menu.

I’ve tried reinstalling the plugin, and trying to exclude other fields, but everything still shows in the context menu. I've also run it on a fresh vault with no snippets or other plugins (apart from Dataview), but still have the same issue. This is with Obsidian v0.12.4 and Supercharged Links 0.2.6.

Really not sure if it's caused by a possible conflict with something, or if it's me completely missing something.

**Comment by mdelobelle** [comment]
Hi! thanks for the bug report. This should be fixed with 0.2.7
Can you confirm this?
