### ISSUE TITLE
[Bug] Incorrect link attribute in file explorer when note names are the same

### ISSUE THREAD

**Issue by lowlight-ua** [mdelobelle/obsidian_supercharged_links#167]
First off, thank you for the very useful plugin.

Attached is the vault that already has this done: [vault.zip](https://github.com/mdelobelle/obsidian_supercharged_links/files/10482610/vault.zip)

Create the following folder/note structure.

* folder "meeting1"
    * note "agenda"
* folder "meeting2"
    * note "agenda"

Assign attribute `date` with _different_ values to both agendas (in YAML frontmatter).

Supercharge the links by the `date` format and style the CSS so that the `date` is appended to the link.

View the file structure in the file explorer.

Problem: all "agenda" links show the same value of the date attribute. (The second agenda should be 2023-01-02.)

![image](https://user-images.githubusercontent.com/23729328/214119636-febb20ca-aaa5-475a-9a9c-b74df117384e.png)

After renaming one of the "agenda"s, so their names are unique, the problem goes away.

**Comment by OptionalM** [comment]
Same as #163
