### ISSUE TITLE
Links to text blocks do not work anymore

### ISSUE THREAD

**Issue by petzi53** [mdelobelle/obsidian_supercharged_links#171]
After installing your plugin, I noticed that I could not generate links to text blocks anymore. I just installed and enabled your plugin, but did not change any settings. I wanted to start to learn your plugin and began reading your tutorial and making some notes. Then I noticed that I was unable to set links to blocks anymore.

After I disabled your plugin, I could link to text blocks again.

**Comment by OptionalM** [comment]
I can't reproduce this. Could you check the Obsidian version are you on? (Settings -> About). How are you generating links to text blocks? Starting with `[[Title^` recommends text blocks to me.

**Comment by petzi53** [comment]
Sorry, I tried again and everything worked fine. It appears to me that the problem resulted from files with similar names. To get the list of blocks to choose, one has to ensure that the string `[[Title^` is unique.
