### ISSUE TITLE
Bug with special character % in live preview.

### ISSUE THREAD

**Issue by OptionalM** [mdelobelle/obsidian_supercharged_links#174]
When a file name contains the percentage symbol (`%`)—which is a valid character for a file name—no links in that file get proper styles applied. This is limited to the live preview edit mode.

The culprit seems to be [this line here](https://github.com/mdelobelle/obsidian_supercharged_links/blob/9a64a66a7ead23402127b548ad4b1026adb446a1/src/linkAttributes/livePreview.ts#L108). `decodeURI(encodedURI)` [throws an error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI#exceptions) if `encodedURI` contains a `%` which isn't encoding anything.

**Comment by OptionalM** [comment]
Removing `decodeURI` (leaving you with `linkText = linkText.split("#")[0];`) fixes the problem for me. But there might be negative knock on effects I'm not seeing yet.

**Comment by HEmile** [comment]
Right... That's a regression caused by #157.
