### ISSUE TITLE
how does one define either or OR in the attribute value?

### ISSUE THREAD

**Issue by zeltak** [mdelobelle/obsidian_supercharged_links#183]
Hi, this seems to me like I missed something but how does one define `either` or `OR` in the attribute value?

ie I have a yaml like this 

---
status:  4
---

I want to style a link if it has either status 4 or status 5, can you do this with a OR or | command or any other way? or of you need to duplicate the link/style for every property level?

thx

Z

**Comment by HEmile** [comment]
More complex rules like this will require CSS, I'm afraid.
