### ISSUE TITLE
Note `(`'s style is applied to regular links

### ISSUE THREAD

**Issue by OptionalM** [mdelobelle/obsidian_supercharged_links#185]
If a Note called `(` exists and has some supercharged styling applied, then all regular links (of the format `[Text](URL)`) also get that styling applied.

![image](https://github.com/mdelobelle/obsidian_supercharged_links/assets/25483088/3d5ac97d-9d1c-44b0-9339-c227c13bc75c)

**Comment by HEmile** [comment]
Huh... So you
- Have a note called (
- Styled this note ( with the emoji
- Every single link of format [Text](Url) get styled that way?

That's a bug... I don't think it's particularly high-priority for now, though. Seems pretty obscure to have a note called ( haha 😅

**Comment by OptionalM** [comment]
Your summary is right on the money. I agree that it's an edge case for everybody except me 😅 
If I find the time I'll fix it myself and get you a PR.
