### ISSUE TITLE
install of this plugin through in app plugin manager(Obsidian 0.12.4 ) fails for 0.2.12

### ISSUE THREAD

**Issue by NikhilSaini38** [mdelobelle/obsidian_supercharged_links#19]
This is the result from console.
![image](https://user-images.githubusercontent.com/7012276/121214351-6219ca00-c8c2-11eb-9f86-16f989a73972.png)

**Comment by NikhilSaini38** [comment]
I think its because the release package is missing

**Comment by NikhilSaini38** [comment]
Also, there is build error.
![image](https://user-images.githubusercontent.com/7012276/121217656-672c4880-c8c5-11eb-8a13-2359821cecca.png)

**Comment by BricoleurSoul** [comment]
I don't have technical expertise of the other commenters, but just came here  to report this issue myself, so can confirm it.

**Comment by mdelobelle** [comment]
Thanks for the report, this should be fixed. can you check that it's ok for you now?

**Comment by BricoleurSoul** [comment]
Incredibly fast response! Thank you.

It works perfectly now.

Kind regards,  and thank you for your work on this plug-in, one of the most useful of the dozen or so that enrich my Obsidian experience.

Kind regards,

David Soul

**Comment by mdelobelle** [comment]
Thank you for your comment @BricoleurSoul !
