### ISSUE TITLE
[BUG] Styling stopped working after 0.11.0 update

### ISSUE THREAD

**Issue by FeralFlora** [mdelobelle/obsidian_supercharged_links#209]
Here are some of my settings:
![image](https://github.com/mdelobelle/obsidian_supercharged_links/assets/33608083/1d6baa06-a651-4bd4-b302-161e3cf53e40)

Hover editor showing note tagged with #workbench but not being styled:
![image](https://github.com/mdelobelle/obsidian_supercharged_links/assets/33608083/496c9e33-0250-49d3-86a8-ce74f64b090f)

Same goes for the other notes visible like Home and Quicknote. I've check that everything is still correct in style settings, which is also apparent from the screenshot of Supercharged Links' settings above.

While these are tag based styles, I think the same goes for properties.

**Comment by HEmile** [comment]
I'd guess this is related to #207 . Can you check if it works again?

**Comment by FeralFlora** [comment]
> I'd guess this is related to #207 . Can you check if it works again?

Yes, I will check later this evening :+1:

**Comment by FeralFlora** [comment]
The update seems to have resolved this.  Styling is again applied as expected 👍

**Comment by HEmile** [comment]
Great!
