### ISSUE TITLE
Performance issue; slow down when there are a lot of links in the current note

### ISSUE THREAD

**Issue by Siirraa** [mdelobelle/obsidian_supercharged_links#220]
I'm a lover of both Supercharged Links and MetaData Menu. I noticed an issue though in performance. I have been looking for a while to find the culprit and I think I nailed it down to SuperCharged Links.

I noticed when I have a large note, the editor becomes sluggish, specially when I add the double brackets `[[` to make a link. This issue is only visible when there are a lot of links, it's fine when there are none or just a few (like <10).

It's easily reproducable in the sandbox vault:

1. Create a new Sandbox vault
2. Turn on community plugins
3. Install SuperCharged links and enable (nothing changed in the settings)

Now create a new note, I named mine "/test"

Notice what happens when you add a link like `[[Code block]]`. It's nice and snappy, as we expect from Obsidian.

Now create a line like this:

`[[Code block]], [[Footnote]], [[Highlighting]], [[Horizontal divider]], [[Emphasis]]`

And copy this line like 100 times (to make it very visible).

Now go to the end of the note and add another link on a blank line by starting the `[[` notice, it takes a while to load and typing is sluggish.

If you now disable SuperCharged Links in the community plugins and close and reopen the note, you will see it's fast again.

So:

- With SuperCharged Links loaded --> Sluggish
- Without SuperCharged Links loaded --> Fast

**Comment by soulsynapse** [comment]
+1, if you have anuppuccin (theme) too it makes it just _brutally_ slow

**Comment by Siirraa** [comment]
I have done some more testing. I think this is not an issue everyone will have. I tend to use a lot of the same links. I have person notes and everytime I "mention" someone, it's a link. Specially in my todo notes, there are lots of mentions of the same person note. If there were a few emails and some interactions, that person is mentioned 20 times easily and when more people are involved this number multiplies.

I don't know exactly how the plugin works, but I suspect all links are parsed when the file has been changed and it seems to happen almost instantly.

A few things come to mind:

- There is no need to parse the same link multiple times, saving a huge amount of processing power
- For me there really is no need to keep the current note updated in near real-time. I'm fine with Obsidian waiting for like 10 seconds after there is no more activity in that note to start updating itself, this also will save a huge amount of processing power, specially if the notes are quite large

Hope either the developer or someone else is able to look at this and make changes.

For now I just disable SuperCharged links and only enable it when I really could use the insights it provides

**Comment by HEmile** [comment]
Hey! Just letting you know I also experienced this regularly. I'll test some workarounds over the coming weeks, hope to get something useful.

**Comment by HEmile** [comment]
Please try out the latest update and see if it improves things for you.

**Comment by Siirraa** [comment]
I just tried the update. Big difference for sure, specially on my test note with lots of links. I'm currently running with SuperCharged links enabled (it was disabled the past days because of this issue), so lets see how it performs in the real world. I'm very optimistic and will report back shortly.

**Comment by Siirraa** [comment]
I'm back again after 3 days or so of testing. It's much better, but in some notes I still encounter significant lag while inserting links in particular, but adding text in general. I have not been able to pinpoint why some have that, while on other notes I cannot notice it at all. First I thought it was just the number of links, which it is not as my testing note has over 200 links in it (many to the same note by the way). I currently suspect the size of the note and some "lines" in particular. Those notes have often quite large code snippits (```) and long log lines (= a line that starts with a date and time and then has a little "story" I write, which can span multiple actual lines on my screen).

I know this is not very helpful, I'll try to isolate what is causing it and report back. I'm quite busy with other stuff though, so that may take a while.

**Comment by Siirraa** [comment]
I think it works fine now. I have been using it the past few weeks without issues. On very large notes with lots of links I still encounter a bit more sluggishness, but it's hardly noticeable. Thanks again for the quick fix!

**Comment by HEmile** [comment]
Happy to hear that!
