### ISSUE TITLE
In the new version of OBSIDIAN, In real -time previews, the dual -chain title of the label does not change the color.

### ISSUE THREAD

**Issue by Peingxious** [mdelobelle/obsidian_supercharged_links#223]
In the new version of OBSIDIAN, use TAG to change the title color.
There is also an A tag to split the title into the title to store information. So to modify the newly added, in SuperCharged-Links-Gen, add a new control of the A tag below the title. Only to repair this problem.
If it is only modified to a tag to A, it will cause other colors to not display before.

![image](https://github.com/mdelobelle/obsidian_supercharged_links/assets/79826986/792dd45e-c8fe-49a8-91a8-594789737a1c)

In fact, manual can be solved, but after clicking the plug-in, SuperCharged-Links-Gen will be automatically updated. Need to be rewritten

**Comment by HEmile** [comment]
This should be solved in the latest update. Please let me know otherwise.

**Comment by gdigesu** [comment]
Hi!

1. It is working on Mac OS
2. It is not working on IOS and on iPad OS
