### ISSUE TITLE
Scrolling panel need

### ISSUE THREAD

**Issue by balola** [mdelobelle/obsidian_supercharged_links#24]
Hi,

My problem is, that if I add lots of preset values in your plugin options panel for one field, with the increasing window size the save button disappears and I am not able to save the data. I  can not scroll down to that button.
I have to use the fileClass method, which is a very good alternative, but not in every case.

Thanks
Füles

**Comment by mdelobelle** [comment]
Hello
Is it still the case with obsidian v0.12.11?
In my case i can scroll down to the save button

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1233240/126739946-5a89552e-e3bf-40b0-9945-b4aec31bab15.png">

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1233240/126739957-b5d5e877-32a0-4305-839b-a48a17af7ce9.png">
