### ISSUE TITLE
Inline fields parsing is not compatible with Dataview's inline fields.

### ISSUE THREAD

**Issue by belen-albeza** [mdelobelle/obsidian_supercharged_links#29]
The widely used [Dataview plugin](https://github.com/blacksmithgu/obsidian-dataview) allows markdown formatting in inline fields names. For example: `**Level**:: Rare` gets parsed as just `level = Rare`, with the markdown formatting parsed out.

However, Supercharged Links don't recognize inline fields with formatting around them. It would be great if both plugins could play nice with each other. Having formatting with fields is quite handy, since they are usually kind of important and I find really useful to highlight them somehow.

**Comment by HEmile** [comment]
Bumping this issue as I had to debug this for someone else. @mdelobelle , I think we should try to use Dataviews inline link parser instead of 'our' own one for this, eg like how this is done in Breadcrumbs.

**Comment by SlRvb** [comment]
Hopefully also using dataview's parser can also help with the issue of the bracket syntax carrying over into the DOM styling:
![dB1C98U1mZ](https://user-images.githubusercontent.com/54087190/147271958-b08bab26-02dd-4f88-9e3c-c1b398aaaba1.png)

and the field editing:
![](https://user-images.githubusercontent.com/54087190/147271518-135289d4-a199-41a7-b8b5-9c64b0ffb3e7.png)

**Comment by mdelobelle** [comment]
this is solved by 0.4.2
