### ISSUE TITLE
Frontmatter arrays are not being recognized

### ISSUE THREAD

**Issue by chi-wi** [mdelobelle/obsidian_supercharged_links#42]
Hey there, loving your plugin!

While arrays in frontmatter like so `tags: ['person']` work just fine, I use an array syntax with 2 spaces for most of my notes which doesn't seem to get recognized :/

```
---
tags:
  - person
---
```
It would be amazing if you could add this :)

**Comment by chi-wi** [comment]
Thanks for the quick edit! I have tested it in a new vault, as to ensure no other plugins are interfering, and while it does now colour everything it is **not persistent**. If I interact with the link, or rather just switch notes back and forth, the e.g. colour disappears.

links.css
```
[data-link-tags*="person"]{
    color: #ff6600 !important;
}
```
This works:
```
tags: [person]
```
This is not persistent:
```
tags:
  - person
```

**Comment by HEmile** [comment]
> This works for tags but not other front matter that uses this YAML array representation e.g 
> ```
> aliases:
> - alias1
> - alias2
> ```
> This is only true when only when getFromInlineField is true because of this [line](https://github.com/HEmile/obsidian_supercharged_links/blob/207007e5a6e6d66fb5f4fc7ce781e9d010f6b1bf/src/linkAttributes/linkAttributes.ts#L18)

Yes, you are right that the frontmatter parsing is different if you use inline fields. @mdelobelle wrote that part of the code, not sure if they can take a look at it? To me it seems best to just use obsidians cache to parse it.

**Comment by chi-wi** [comment]
It's working now! Thank you for the fix :)
