### ISSUE TITLE
[BUG]: Populate symbols in explorer only after interaction 

### ISSUE THREAD

**Issue by cogscides** [mdelobelle/obsidian_supercharged_links#43]
When I'm open obsidian on mobile supercharged links show prepended symbols in note preview, but not in explorer. Only after opening any note from explorer it start showing symbols.

UPD: for desktop it also don't push symbols in titles that in other folders. In other words when I'm open obs, it works in one folder, but when I'm open another one it doesn't. Only after opening note from this second folder plugin start working in explorer.

Whould be awesome if it will be fixed. It will change huge part of my note titles readability 🖤

**Comment by cogscides** [comment]
https://user-images.githubusercontent.com/50235526/149328349-c825002a-afbd-4e80-89e8-347e0d3c9920.mp4

**Comment by HEmile** [comment]
Should be fixed in latest version!
