### ISSUE TITLE
Suggestion: Autocomplete from predefined values in editor

### ISSUE THREAD

**Issue by kepano** [mdelobelle/obsidian_supercharged_links#45]
Feature idea:

Allow users to access the predefined values for a field from the editor. This could use a trigger character similar to creating a new link with `[[` or the `@` used by Natural Language Dates plugin.

Example:
If I type `country::` automatically show the autocomplete list of predefined values

**Comment by ooker777** [comment]
so is this implemented yet?

**Comment by cogscides** [comment]
I think it more relate to the metaedit plugin. But no, it's not implemented. Maybe other plugins could apply this

> so is this implemented yet?

**Comment by HEmile** [comment]
I don't think this is something for Supercharged Links, honestly. Other plugins have looked into autocompletion, like Various Complements and Completr. This sounds more like a good FR for plugins like that.

**Comment by mdelobelle** [comment]
This feature is now available in https://github.com/mdelobelle/metadatamenu/releases/tag/0.0.4 (this plugin is an "extract" of SCL fields options features an can be tested with BRAT)

**Comment by mdelobelle** [comment]
The approach is very similar indeed but based on folders. Thank you for the information
