### ISSUE TITLE
Add ignored directories/files

### ISSUE THREAD

**Issue by mikkovedru** [mdelobelle/obsidian_supercharged_links#46]
This is a continuation of the #33 issue.

Having links being supercharged in the File Explorer is an amazing addition! Thank you @HEmile one more time!

But now I have noticed an issue with this feature. It works really well even when it would be undesirable - like with the template directory/files. Since those files contain e.g. a full list of status attributes (so I could simply delete the unnecessary ones), the template directory looks like a Christmas tree. :-)
![image](https://user-images.githubusercontent.com/2521942/137541310-452db79b-9987-441d-bca4-147892232c38.png)

Would it be possible to create the "These directories/files will be ignored by the plugin" feature? 

https://github.com/dvcrn/obsidian-filename-heading-sync has a really nice Regex ignore feature. It's worth it to check it out for inspiration if you feel like it. :-) For my purposes, the feature can be much simpler - one field with one lonely template directory.

Thank you for considering my request!

**Comment by HEmile** [comment]
Going to close this now as the latest update allows you to style by path. You can restore the default styling by targeting the template folder path to 'exclude' folders.

**Comment by mikkovedru** [comment]
Thank you, @HEmile !
