### ISSUE TITLE
FR: Minor changes to Field Options Modal

### ISSUE THREAD

**Issue by brimwats1** [mdelobelle/obsidian_supercharged_links#47]
I would like it if the field options modal was usable through the keyboard. Here's an example. In this example I want to change CreativeWorkType, but i need to use the mouse and cant scroll with the keyboard:
![uBBxESSU5L](https://user-images.githubusercontent.com/49103046/137811142-399a0cfd-06ac-4ef7-90e4-dbac71e8faa6.gif)

it would be great if I could just select the thing I wanted to change

**Comment by HEmile** [comment]
The Link context menu extra options functionality is deprecated and will be removed in a future version of the plugin. We recommend using the [MetaEdit plugin](https://github.com/chhoumann/MetaEdit) instead. I'm closing this issue because it is related to this functionality.

**Comment by brimwats** [comment]
great! thanks
