### ISSUE TITLE
Could you please add more examples of using the Plugin

### ISSUE THREAD

**Issue by vkbytes** [mdelobelle/obsidian_supercharged_links#5]
### More example of the plugin
Sorry to mention this but I am a bit of noob on css. I was trying to replicate the visual example that you have shown about the plugin. However I was not able to write the correct css for it. 

I am sure someone else trying to understand the plugin might be facing a similar issue. It would be good if you could add a bit of more explanation and css example for the visual that is shown on the readme. Might be helpful for a lot of people trying to incorporate the plugin in the usage. Btw I think this is a fantastic plugin. Just a bit more documentation will speed up its adoption.

**Comment by mdelobelle** [comment]
Hi thank you for your message, you can find a more "step by step" explanation on the forum. 
https://forum.obsidian.md/t/supercharged-links-showcase/18219
could you try to follow this steps and give me some feedback?

**Comment by vkbytes** [comment]
@mdelobelle Thank you for the link, I think it does have more explanation and easy way to understand the plugin better. In fact I raised the issue because I don't think people found the forum post. But definitely, a lot easier to follow the forum post then the readme.

**Comment by vkbytes** [comment]
@mdelobelle I just mentioned the forum post on the Discord channel as well
https://discord.com/channels/686053708261228577/805952223124520961/843275350783557642

**Comment by mdelobelle** [comment]
Thanks. I'll update the readme in the next version
