### ISSUE TITLE
dataview style inline attribute not working

### ISSUE THREAD

**Issue by bpriyum** [mdelobelle/obsidian_supercharged_links#61]
The plugin should allow styling links by adding dataview style inline attributes. But this is not happening.

I used the attribute note_type:: question in one note. And I added yaml style metadate using note_type: question in another note.

The first one was not styled based on the attribute.

**Comment by HEmile** [comment]
Is this happening only in live preview? It is a known limitation that it doesn't work there. Also bold inline attributes don't work

**Comment by mdelobelle** [comment]
this is solved with 0.4.2

**Comment by brunayfy** [comment]
This was not solved as of now. Supercharged  0.8.0 Dataview v0.5.46 and obsidian v0.15.9  and macOs Monterey 12.6
