### ISSUE TITLE
[Bug] Turning off "Enable in Editor" breaks Obsidian

### ISSUE THREAD

**Issue by MichaBrugger** [mdelobelle/obsidian_supercharged_links#66]
Hey there!
Thanks for creating such a cool plugin, I love it!

However, I found a bug that I thought you might want to know about:
When turning the "Enable in Editor" setting off, Obsidian can't be opened anymore. It will just show the endless reload screen (the only thing that helps is to delete the supercharged plugin folder from Obsidian directly).

I tried this 4-5 times just to be sure and, at least for me, it happens every time (System: Arch Linux, Obsidian: 0.13.19, SCL: 0.4.0).

![image](https://user-images.githubusercontent.com/46029522/148980792-1e117fe8-ca08-4456-be5e-ece6d660f31c.png)

**Comment by HEmile** [comment]
Should be fixed in 0.4.1 .
