### ISSUE TITLE
Bug: Data link text attribute no longer being applied in 0.4.1

### ISSUE THREAD

**Issue by Aaron-Bopp** [mdelobelle/obsidian_supercharged_links#69]
Hello all, so this issue appeared in the most recent update. I am surprised there isn't already an issue for this, so maybe I am doing something differently/wrong. 

On previous version
![image](https://user-images.githubusercontent.com/48270139/149636108-f721b3ed-6822-4a59-a900-55adc79d817f.png)

```html
<span data-link-aliases="" data-link-tags="#created/evergreen/2021/11/06 #review #node/evergreen #TO/EXPLORE/WATCH #TO/TEND/CONNECT #EVER/GROWING" data-link-data-href="Humans are primarily irrational, illogical, emotional beings" class="data-link-text"><span class="cm-underline">Humans are primarily irrational, illogical, emotional beings</span></span>
```
On 0.4.1
![image](https://user-images.githubusercontent.com/48270139/149636134-4e0aaa7c-eb8f-454b-84d0-49a993402652.png)

```html
<span data-link-tags="#created/evergreen/2021/11/06 #review #node/evergreen #TO/EXPLORE/WATCH #TO/TEND/CONNECT #EVER/GROWING" data-link-aliases="" data-link-data-href="Humans are primarily irrational, illogical, emotional beings"><span class="cm-underline">Humans are primarily irrational, illogical, emotional beings</span></span>
```

The online difference is a lack of the data-link-text class in the newer version.

Here is the relevant css
```css
.data-link-text[data-link-tags*="evergreen"] {
    color: rgba(71, 179, 221, 0.904) !important;
    text-decoration: none;
}
```
Should I not be relying on this attribute, or is this a bug?

**Comment by HEmile** [comment]
That may have gotten removed in a refactor. I'll look tomorrow.

**Comment by HEmile** [comment]
Yeah, you are right it is no longer applied. It is most likely not needed anymore. Can you check just removing the `.data-link-text` class in the selector and see if that works for you?

**Comment by Aaron-Bopp** [comment]
Yep, it is unneeded. Thanks for the help!
