### ISSUE TITLE
Feature Request: Support Recent files plugin

### ISSUE THREAD

**Issue by chrisgrieser** [mdelobelle/obsidian_supercharged_links#72]
it would be fantastic if supercharged links also supported the [recent files plugin](https://github.com/tgrosinger/recent-files-obsidian) many users have in their sidebar. 🙂

**Comment by chrisgrieser** [comment]
thanks 💙

**Comment by chrisgrieser** [comment]
I just updated and I can't get supercharged links to work in the sidebar? SInce there is no new setting for it, I tried checking everything (enable in file browser, enable in backlinks panel etc.), but the console still shows no datalink-attributes for items in the recent files pane?

**Comment by HEmile** [comment]
Strange, it's definitely working for me. It should be enabled by the backlinks option.

**Comment by chrisgrieser** [comment]
huh, seems it didn't install properly, after an re-install it works now.

Anyway, might wanna add to the settings description that "backlinks" enables showing the icons in recent files :)

**Comment by HEmile** [comment]
Ah, happy to hear that! I'll test a bit more too with the installation. 
And yeah i just changed the description of that setting to be more up to date with current affairs,haha.
