### ISSUE TITLE
Bug: `updateContainer()` causing lag when typing in note

### ISSUE THREAD

**Issue by shabegom** [mdelobelle/obsidian_supercharged_links#74]
<img width="1264" alt="Screen Shot 2022-01-18 at 6 30 58 PM" src="https://user-images.githubusercontent.com/5445691/150035484-04069918-e3d0-4cdd-8df6-8bc63dc66395.png">

I was getting some bad lag while typing into a note. The performance snapshot shows `updateContainer` firing repeatedly followed by `updateDivExtraAttributes`. When I disable the plugin the lag goes away.

I have a suspicion this is due to triggering on `metadataCache` changes, which can happen very frequently. One possible option could be to use the APIs `debounce` function and debounce these calls.

**Comment by shabegom** [comment]
Ok I'm not seeing this behaviour in all notes. Makes me wonder if it is dependant on the number of links in a given note?

Yeah I think it was because I had a lot of backlinks in a note...

**Comment by HEmile** [comment]
Thanks for the report! I've reverted to the earlier (more efficient) code for the backlinks panel. Can you see if this solves the performance issues for you?

**Comment by shabegom** [comment]
Yep! looks like the lag is gone now. Thanks!
