### ISSUE TITLE
Performant drop consistently every 3 seconds after update 0.4.6

### ISSUE THREAD

**Issue by shaggyfeng** [mdelobelle/obsidian_supercharged_links#75]
Obsidian v0.13.19
Editor legacy mode on
I check all the plugin, once I disable supercharged_links and enable an older version, no more performant drop.

**Comment by HEmile** [comment]
Hi, thank you for the report. Can you test out the latest version 0.4.7, see if it is better there?

**Comment by shaggyfeng** [comment]
> Hi, thank you for the report. Can you test out the latest version 0.4.7, see if it is better there?

Thank you, the performance issue has been fixed with 0.4.7.
