### ISSUE TITLE
Feature Request: Show icons in Quick Switchers?

### ISSUE THREAD

**Issue by chrisgrieser** [mdelobelle/obsidian_supercharged_links#76]
Since adding the links to sidebar tabs seems easy (e.g. #72), I was wondering whether it is also possible to add icons to the Quick Switcher (and Quick Switcher Plugins like "Another Quick Switcher)? They are basically the only place where I now see my files without Supercharged Styling.

**Comment by HEmile** [comment]
Should work in next version

https://user-images.githubusercontent.com/1289165/151440527-f5d3f28b-dec0-4604-aed7-672aa7abfe98.mov

**Comment by chrisgrieser** [comment]
Look fantastic! Would you make it work with ["Another Quick Switcher"](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher), too? 🥺

**Comment by HEmile** [comment]
Oh yeah, forgot to test that one! Is supported now :)

**Comment by chrisgrieser** [comment]
💙
