### ISSUE TITLE
Not working - 2 properties that go with "::after"?

### ISSUE THREAD

**Issue by KennyDenvers** [mdelobelle/obsidian_supercharged_links#82]
Hi!
I am beginner with this, exploring this and finding this very interesting! 
I have encountered this problem (see "code" below), however, that there appears to be some sort of conflict with the 2 "items" that are supposed to show up "::after" the link. In my case below these are the "head icon" connected with "age=42" and the "phone icon" connected with "next-actions=call". Why don't they both show after the link? How could this work (showing both)?

And does the "~" have anything to do with that? (the only difference that I currently see; what does the "~" do anyway?)

a.internal-link[data-link-category~="people"]::before{
  content: "👤"
}

a.internal-link[data-link-age="42"]::after{
  content: "👨"
}

a.internal-link[data-link-next-actions~="call"]{
  color:yellowgreen
}

a.internal-link[data-link-next-actions~="call"]::after{
  content: "☎️"
}

:not(:empty)[data-link-aliases]{
    color: white;
    background-color: rgb(29, 29, 129);
    border-radius: 18px;
    padding: 3px 8px;
}

**Comment by HEmile** [comment]
Unfortunately, having multiple ::after matches does not join them in CSS... So it chooses the one at the bottom (the phone, I suppose). If you really need both, I think you can do 

```css
a.internal-link[data-link-next-actions~="call"][data-link-age="42"]::after{
content: "👨☎️"
}
```
