### ISSUE TITLE
Emoji symbol for "category: people" not showing in file navigation view

### ISSUE THREAD

**Issue by KennyDenvers** [mdelobelle/obsidian_supercharged_links#83]
Hi!
I am just exploring the possibilities of this plugin by trying out the initially suggested use cases. The 👤icon is not showing in file navigation although I have all options activated in the plugin options.

**Comment by HEmile** [comment]
I don't think I can reproduce this unfortunately. Have you tried reloading Obsidian? If it still doesn't show up, something must be going wrong. 

<img width="602" alt="image" src="https://user-images.githubusercontent.com/1289165/151770042-2c2e021a-29a3-45a6-b2ca-b7eb8392995f.png">

**Comment by KennyDenvers** [comment]
Thanks so much for your replies!

I've restarted Obsidian several times - deactivated and reactivated the buttons for displaying the supercharged links in file navigation etc. -- nothing helped so far. I've also used a css snippet with only the "people head" code in it. Still, this is the result:
![image](https://user-images.githubusercontent.com/90445513/151778524-3459d6ee-e990-487e-b8d7-673122d95c3d.png)

Would be great if you had another idea. (Current code copied below:)

![image](https://user-images.githubusercontent.com/90445513/151779039-030770a5-ab41-475f-999b-0fb110622472.png)

a.internal-link[data-link-category~="people"]::before{
  content: "👤"
}

**Comment by KennyDenvers** [comment]
Hi! I've got this to work with this modification (deleting the "a.internal-link" piece):

Could you tell what are the benefits of either way to do it?

![image](https://user-images.githubusercontent.com/90445513/151786557-bdfccb68-131c-4f99-bfa2-cf16b457d9f8.png)

**Comment by HEmile** [comment]
The right way to do this is like you have in the picture! However, I'd recommend changing the second one to `.data-link-icon[data-link-category ~="people"]::before {` otherwise you'll get issues in live preview.

Btw, I'm working right now on making this process easier (ie not requiring CSS).
