### ISSUE TITLE
Could we get autocomplete for tags in the update windows?

### ISSUE THREAD

**Issue by ghost** [mdelobelle/obsidian_supercharged_links#91]

**Comment by HEmile** [comment]
Do you mean here?

![image](https://user-images.githubusercontent.com/1289165/153213027-96c6a07a-406f-468f-aa64-01f12318866d.png)

**Comment by aisle9** [comment]
No, here
![Screenshot 2022-02-09 202502](https://user-images.githubusercontent.com/36053698/153275589-346def61-c75a-418c-a4af-2439cdacc36e.png)
.

**Comment by HEmile** [comment]
The Link context menu extra options functionality is deprecated and will be removed in a future version of the plugin. We recommend using the [MetaEdit plugin](https://github.com/chhoumann/MetaEdit) instead. I'm closing this issue because it is related to this functionality.
