### ISSUE TITLE
Fields in list support

### ISSUE THREAD

**Issue by subhinay** [mdelobelle/obsidian_supercharged_links#93]
I don't know whether this will fall under a bug or is it a new feature request, but here it is:

I have:
```
- Type:: [[whatever]]
- Category:: [[whathaveyou]]
```
and so on.

Thing is, when I update the field through Supercharged, it removes the bullet. Any ideas?

It also removes the one set of brackets ([]) from one existing property leaving [whatever].

I am using lists because:
1. I don't want to use YAML.
1. I use Markdown's double space as new line option.
1. If I am using multi field values then either I add two spaces to every option or not at all. Otherwise, the next field is going to be cramed in the same line in preview.

**Comment by HEmile** [comment]
The Link context menu extra options functionality is deprecated and will be removed in a future version of the plugin. We recommend using the [MetaEdit plugin](https://github.com/chhoumann/MetaEdit) instead. I'm closing this issue because it is related to this functionality.
