### ISSUE TITLE
bug: cursor jumps when inserting text after wikilink

### ISSUE THREAD

**Issue by liamcain** [mdelobelle/obsidian_supercharged_links#96]
## Steps to Repro

CM6 Editor only.

Create a line with `[[foobar]]`.

On the same line, start typing the word `test`, the cursor will be pushed to characters to the left and you will end up typing `est t`. This happens consistently.

**Comment by HEmile** [comment]
Hm... i can't say i can directly reproduce this, but i do remember having this issue months ago. However I've not experienced it for ages and can't recall what i changed. Are you sure it's supercharged that causes it? Also does foobar have something like prepend emojis?

**Comment by liamcain** [comment]
Yeah I tested it in a new vault with just supercharged links installed and no configuration. Also checked if it was vim mode related (it happened regardless though). I have had the plugin enabled for a long time in my main vault though, and I’m only noticing it recently…so I’ll try to eliminate more factors.

**Comment by HEmile** [comment]
Is it possible to make a quick video so I'm sure I'm reproducing it right?

**Comment by liamcain** [comment]
I just created a new vault with just the supercharged links plugin enabled and nothing else:

https://user-images.githubusercontent.com/693981/156929207-c1d19cf2-37d2-4aee-9f60-f37e6e199a55.mov

**Comment by Abeltjes** [comment]
I just started to experience the exact same problem. It stopped when I disabled the supercharged links plugin in my vault.

**Comment by HEmile** [comment]
You know what, since the last insider release I'm experiencing the same... @Abeltjes @liamcain what Obsidian versions are you on?

**Comment by Abeltjes** [comment]
Yeah, the newest: v.0.13.29. I use the supercharge to prepend emojis, but it also happened with 'clean' links.

**Comment by HEmile** [comment]
Should be fixed in the latest update. Can you check?

**Comment by Abeltjes** [comment]
Yes, works as a charm again! Thanks so much! Not only supercharged, also super quick!
